[tools]
go = "latest"
lua = "latest"
node = "lts"
# uv = "latest"
rust = "latest"

[settings]
trusted_config_paths = ["~/.local/share/chezmoi/dot_config/mise/config.toml"]
idiomatic_version_file_enable_tools = ["python"]
# python.uv_venv_auto = true
# experimental = true
